
DROP TABLE IF EXISTS recipe_ingredients;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS mealplans;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS calendars;